export const propertyData = [
  {
    id: "1",
    thumbnail: "/assets/property-1.svg",
    views: "41,172",
    rating: "3.82",
    title: "Sushant Lok 2, Gurgaon",
    date: "Apr 5 - 10",
    price: "1.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-2.svg",
      "/assets/property-1.svg",
    ],
    lat: 19.075983,
    lng: 72.877655,
  },
  {
    id: "2",
    thumbnail: "/assets/property-2.svg",
    views: "8,402",
    rating: "5.0",
    title: "Rainbow Heights, HSR",
    date: "Mar 9 - 14",
    price: "2.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-2.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-1.svg",
    ],
    lat: 12.971599,
    lng: 77.594566,
  },
  {
    id: "3",
    thumbnail: "/assets/property-3.svg",
    views: "12,648",
    rating: "2.82",
    title: "Walden, Colorado, US",
    date: "Mar 3 - 8",
    price: "3.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-2.svg",
    ],
    lat: 18.52043,
    lng: 73.856743,
  },
  {
    id: "4",
    thumbnail: "/assets/property-4.svg",
    views: "6,483",
    rating: "5.0",
    title: "Poggibonsi, Italy",
    date: "Apr 26 - May 1",
    price: "4.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-2.svg",
      "/assets/property-1.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
    ],
    lat: 13.08268,
    lng: 80.270721,
  },
  {
    id: "5",
    thumbnail: "/assets/property-1.svg",
    views: "41,172",
    rating: "3.82",
    title: "Sushant Lok 2, Gurgaon",
    date: "Apr 5 - 10",
    price: "1.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 19.075983,
    lng: 72.877655,
  },
  {
    id: "6",
    thumbnail: "/assets/property-2.svg",
    views: "8,402",
    rating: "5.0",
    title: "Rainbow Heights, HSR",
    date: "Mar 9 - 14",
    price: "2.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 12.971599,
    lng: 77.594566,
  },
  {
    id: "7",
    thumbnail: "/assets/property-3.svg",
    views: "12,648",
    rating: "2.82",
    title: "Walden, Colorado, US",
    date: "Mar 3 - 8",
    price: "3.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 18.52043,
    lng: 73.856743,
  },
  {
    id: "8",
    thumbnail: "/assets/property-4.svg",
    views: "6,483",
    rating: "5.0",
    title: "Poggibonsi, Italy",
    date: "Apr 26 - May 1",
    price: "4.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 13.08268,
    lng: 80.270721,
  },

  {
    id: "9",
    thumbnail: "/assets/property-1.svg",
    views: "41,172",
    rating: "3.82",
    title: "Sushant Lok 2, Gurgaon",
    date: "Apr 5 - 10",
    price: "1.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-2.svg",
      "/assets/property-1.svg",
    ],
    lat: 19.075983,
    lng: 72.877655,
  },
  {
    id: "10",
    thumbnail: "/assets/property-2.svg",
    views: "8,402",
    rating: "5.0",
    title: "Rainbow Heights, HSR",
    date: "Mar 9 - 14",
    price: "2.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-2.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-1.svg",
    ],
    lat: 12.971599,
    lng: 77.594566,
  },
  {
    id: "11",
    thumbnail: "/assets/property-3.svg",
    views: "12,648",
    rating: "2.82",
    title: "Walden, Colorado, US",
    date: "Mar 3 - 8",
    price: "3.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-2.svg",
    ],
    lat: 18.52043,
    lng: 73.856743,
  },
  {
    id: "12",
    thumbnail: "/assets/property-4.svg",
    views: "6,483",
    rating: "5.0",
    title: "Poggibonsi, Italy",
    date: "Apr 26 - May 1",
    price: "4.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-2.svg",
      "/assets/property-1.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
    ],
    lat: 13.08268,
    lng: 80.270721,
  },
  {
    id: "13",
    thumbnail: "/assets/property-1.svg",
    views: "41,172",
    rating: "3.82",
    title: "Sushant Lok 2, Gurgaon",
    date: "Apr 5 - 10",
    price: "1.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 19.075983,
    lng: 72.877655,
  },
  {
    id: "14",
    thumbnail: "/assets/property-2.svg",
    views: "8,402",
    rating: "5.0",
    title: "Rainbow Heights, HSR",
    date: "Mar 9 - 14",
    price: "2.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 12.971599,
    lng: 77.594566,
  },
  {
    id: "15",
    thumbnail: "/assets/property-3.svg",
    views: "12,648",
    rating: "2.82",
    title: "Walden, Colorado, US",
    date: "Mar 3 - 8",
    price: "3.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 18.52043,
    lng: 73.856743,
  },
  {
    id: "16",
    thumbnail: "/assets/property-4.svg",
    views: "6,483",
    rating: "5.0",
    title: "Poggibonsi, Italy",
    date: "Apr 26 - May 1",
    price: "4.5 Cr",
    address: "Sector 57, Gurgaon",
    images: [
      "/assets/property-1.svg",
      "/assets/property-2.svg",
      "/assets/property-3.svg",
      "/assets/property-1.svg",
      "/assets/property-2.svg",
    ],
    lat: 13.08268,
    lng: 80.270721,
  },
];
